### ISSUE TITLE
NPE during initialization

### ISSUE THREAD

**Issue by fadils** [tumblr/Remember#17]
Any chance what might cause this following NPE?
I sometimes get this. Not sure as well how to reproduce this. But I thought, you might know.

```
Caused by: java.lang.NullPointerException
    at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:821)
    at java.util.concurrent.ConcurrentHashMap.putAll(ConcurrentHashMap.java:894)
    at com.tumblr.remember.Remember.initWithContext(Remember.java:82)
    at com.tumblr.remember.Remember.init(Remember.java:107)
```

**Comment by ericleong** [comment]
Do you know which Java or Android version you're running? The stack trace suggests the bug is in `ConcurrentHashMap`, and looking at [the Android source for 6.0.1_r5](https://android.googlesource.com/platform/libcore.git/+blame/android-6.0.1_r5/luni/src/main/java/java/util/concurrent/ConcurrentHashMap.java#821) it doesn't seem like line 821 has changed recently, but it's also part of the wrong method (`containsKey()` rather than `putVal()`), although there haven't been any changes in `putVal()` either.

I hope this isn't some strange difference between [OpenJDK and Apache Harmony](http://arstechnica.com/tech-policy/2016/01/android-n-switches-to-openjdk-google-tells-oracle-it-is-protected-by-the-gpl/)...

**Comment by fadils** [comment]
Android version: Android 5.0
Device: Xperia Z3 (SO-01G)

**Comment by ericleong** [comment]
[Line 821 in the source for Android `android-5.0.0_r7`](https://android.googlesource.com/platform/libcore.git/+blame/android-5.0.0_r7/luni/src/main/java/java/util/concurrent/ConcurrentHashMap.java#821) suggests that either the key or the value is null and [the calling line in Remember (line 82)](https://github.com/tumblr/Remember/blob/master/remember/src/main/java/com/tumblr/remember/Remember.java#L82) passes [a `Map<String, ?>` from `SharedPreferences.getAll()`](http://developer.android.com/reference/android/content/SharedPreferences.html#getAll%28%29). We know the `Map<>` isn't `null` because [it would fail on line 892](https://android.googlesource.com/platform/libcore.git/+blame/android-5.0.0_r7/luni/src/main/java/java/util/concurrent/ConcurrentHashMap.java#892), so what remains is either a null key or value in your dataset, which matches the error thrown.

I think there's a good argument for this library to guard against this case, but doing so has an adverse performance impact - it needs to loop over all the items in `SharedPreferences` to ensure neither the entry nor the key are `null`.

**Comment by alashow** [comment]
got this from crashlytics too.

http://crashes.to/s/365e1b3c066
